(set-face-attribute 'markup-title-0-face nil :height 1.5)
(set-face-attribute 'markup-title-1-face nil :height 1.4)
(set-face-attribute 'markup-title-2-face nil :height 1.3)
(set-face-attribute 'markup-title-3-face nil :height 1.2)
(set-face-attribute 'markup-title-4-face nil :height 1.1)
(set-face-attribute 'markup-title-5-face nil :height 1.0)
(set-face-attribute 'markup-meta-face nil :height 1.0)
(set-face-attribute 'markup-meta-hide-face nil :height 1.0)
